config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: 'events#index'
  resources :events do
    post '/attends', to: 'events#attend', as: 'attend'
  end

  get 'users/id' => 'users#show', as: 'profile'

  resources :attends, only: %i[create destroy]


end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable

  has_many :created_events, class_name: 'Event', dependent: :destroy

  # Event attends

  has_many :attends, foreign_key: :attendee_id, class_name: 'Attend', dependent: :destroy
  has_many :attended_events, through: :attends

  validates :email, presence: true, uniqueness: { case_sensitive: false }

  def attended?(event)
    event.attendees.include?(self)
  end

  def not_attended?(event)
    event.attendees.exclude?(self)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_saniti  get 'attends/create'
  # get 'attends/destroy'zer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, :see_attended_events, :see_created_events

  def profile
    @user = current_user
  end

  def show; end

  private

  def see_created_events
    @created_events = @user.created_events.order(event_date: :desc)
  end

  def see_attended_events
    @attended_events = @user.attended_events.order(event_date: :desc)
  end

  def set_user
    @user = User.find(params[:format])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_session_manager.html.erb
<% if current_user %>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      @<%= current_user.email %>
    </a>
    <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdown">
      <li><%= link_to 'Profile', profile_path(current_user), class:'dropdown-item' %></li>
      <li><%= link_to 'Edit Account', edit_user_registration_path, class:'dropdown-item' %></li>
      <li><hr class="dropdown-divider"></li>
      <li><%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class:'dropdown-item' %></li>
    </ul>
  </li>
<% else %>
  <li class="nav-item">
    <%= link_to 'Sign Up', new_user_registration_path, class:'nav-link' %>
  </li>
  <li class="nav-item">
    <%= link_to 'Login', new_user_session_path, class:'nav-link' %>
  </li>
<% end %>

app/views/users/show.html.erb
<div class="container">
  <h2 class="align-center">@<%= @user.email %></h2><br /><br />
  <h4>Created events: </h4>
  <% @created_events.each do |event| %>
    <h5><%= link_to "#{event.title}", event, class: 'link-dark' %></h5>
  <% end %>
  <br /><br />

  <h5>Upcoming events:</h5>
  <% @upcoming_events = @attended_events.where("event_date >= ?", Time.zone.now) %>
  <% if @upcoming_events.any? %>
    <% @upcoming_events.each do |event| %>
      <h5><%= link_to "#{event.title}", event, class: 'link-dark' %></h5>
    <% end %>
  <% else %>
    <p>No upcoming events</p>
  <% end %><br /><br />
  <h5>Past events:</h5>
  <% @past_events = @attended_events.where("event_date < ?", Time.zone.now) %>
  <% if @past_events.any? %>
    <% @past_events.each do |event| %>
      <h5><%= link_to "#{event.title}", event, class: 'link-dark' %></h5>
    <% end %>
  <% else %>
    <p>No past events</p>
  <% end %>
</div>