config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: 'events#index'
  resources :events do
    post '/attends', to: 'events#attend', as: 'attend'
  end

  get 'users/id' => 'users#show', as: 'profile'

  resources :attends, only: %i[create destroy]


end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  validates :title, :description, :location, :event_date, presence: true
  belongs_to :creator, class_name: 'User', foreign_key: :user_id

  has_many :attendances, foreign_key: :event_id, class_name: 'Attend'
  has_many :attendees, through: :attendances

  scope :past_events, -> { where('event_date <= ?', Time.zone.now).order(event_date: :desc) }
  scope :upcoming_events, -> { where('event_date > ?', Time.zone.now).order(event_date: :desc) }

  def private_event?
    event_type
  end

  def user_list
    @user_list = User.where('id != ?', current_user.id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: %i[show index]
  before_action :set_event, only: %i[show update edit destroy attend]

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      redirect_to @event, notice: 'Event successfully created!'
    else
      render :new, status: 422
    end
  end

  def index
    @events = Event.all.order(event_date: :desc)
  end

  def show
    @attendees = @event.attendees
  end

  def edit; end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'Event updated and saved!'
    else
      render :edit, status: 422
    end
  end

  def destroy
    @event.destroy
    redirect_to root_path, status: 303, notice: 'Event deleted!'
  end


  private

  def event_params
    params.require(:event).permit(%i[title description location event_date event_type])
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_attend.html.erb
<%= form_with model: current_user.attends.build(event_id: event.id, attendee_id: current_user.id) do |f| %>
  <%= f.hidden_field :event_id %>
  <%= f.hidden_field :attendee_id, value: current_user.id %>
  <%= f.submit 'Attend to event!', class: 'btn btn-success mt-2 mb-2' %>
<% end %>

app/views/events/_attend_buttons.html.erb
<% if current_user.attended?(event) %>
  <%= render 'cancel_attend' %>
<% else %>
  <%= render 'attend', event: event %>
<% end %>

app/views/events/_cancel_attend.html.erb
<%= button_to "Cancel", attend_path, method: :delete, title: 'Delete', class: 'btn btn-danger mt-2 mb-2' %>

app/views/events/_event.html.erb
<div>
  <h2><%= link_to "#{event.title}", event, class: 'link-dark' %></h2>
  <p><%= event.description %></p>
  <p>Will be happy to see you!</p>
  <p>Event date: <%= event.event_date %></p><br />
  <p>Event held by: <%= event.creator.email %></p>
</div>

app/views/events/_form.html.erb
<div class="container">
  <%= simple_form_for event do |f| %>
    <% if event.errors.any? %>
      <div class="validation_errors">
        <h2><% pluralize(event.errors.count, 'error') %> prohibited this event from being saved:</h2>
        <ul>
          <% event.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :location %>
    <%= f.input :event_date, as: :date, html5: true %>
    <%= f.input :event_type, as: :radio_buttons, collection: [['Yes', true], ['No', false]], label: 'Is your event private?' %>
    <%= f.button :submit, class: 'btn btn-success mt-2 mb-2' %>
  <% end %>
</div>

app/views/events/_invite.html.erb
<h3 class="text-center">Invite users</h3>
<%= form_with model: event.attendances.build(event_id: event.id) do |f| %>
  <%= f.hidden_field :event_id %>
  <%= f.collection_check_boxes :attendee_id, User.includes(:attends).where('users.id != ?', current_user.id).order(:email).select { |user| user.not_attended?(event) }, :id, :email do |b| %>
    <li>
      <%= b.check_box %>
      <%= b.label %>
    </li>
  <% end %>
  <%= f.submit 'Invite users', class: 'btn btn-success mt-2 mb-2' %>
<% end %>

app/views/events/edit.html.erb
<div class="container">
  <h1>Edit event information</h1>
  <%= render form, event: @event %>
  <br />
  <div class="button-group float-end">
    <%= link_to 'Show this event', @event, class: 'btn btn-success mt-2 mb-2' %>
  </div>
</div>

app/views/events/index.html.erb
<h1 class="text-center">Upcoming events</h1>
<div class="d-grid gap-2">
  <% Event.upcoming_events.each do |event| %>
    <div class="container p-2 bg-light-border">
      <%= render event %>
    </div>
  <% end %>
</div><br /><br /><br />
<h1 class="text-center">Past events</h1>
<div class="d-grid gap-2">
  <% Event.past_events.each do |event| %>
    <div class="container p-2 bg-light-border">
      <%= render event %>
    </div>
  <% end %>
</div>

app/views/events/new.html.erb
<div class="container">
  <h1>Create new event</h1>
  <%= render 'form', event: @event %>
  <br />
</div>

app/views/events/show.html.erb
<div class="container-fluid">
  <div class="row align-items-start">
    <div class="col">
      <%= render @event %>
      <% if user_signed_in? %>
        <%= render 'cancel_attend' if @event.private_event? && current_user.attended?(@event)%>
        <%= render 'attend_buttons', event: @event unless @event.private_event? %>
      <% end %>
    </div>
    <div class="col">
      <p>People attended on this event:</p>
      <% @attendees.each do |att| %>
        <p><%= att.email %></p>
      <% end %>
    </div>
    <% if current_user == @event.creator %>
      <div class="col">
        <%= render 'invite', event: @event %>
        <br /><br />
        <%= button_to 'Delete event', event_path, method: :delete,
                      data: { confirm: "Are you sure?" }, class: 'btn btn-danger' %>
      </div>
    <% end %>
  </div>
</div>